name: cosmetics_shop
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.otf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Medium.ttf
    - family: VelaSans
      fonts:
        - asset: fonts/VelaSans-Regular.ttf
